import './globals.css'
import type { Metadata } from 'next'
import Sidebar from "@/components/Sidebar";
import ModalProvider from "@/components/modals/ModalProvider";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='font-gg-sans flex flex-row text-white bg-discord-gray-1'>
        <ModalProvider/>
        <Sidebar/>
        {children}
      </body>
    </html>
  )
}
